name: Package and deploy zip of connector to PROD

on:
  push:
    branches:
      - prod

jobs:
  package-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
      - name: Install upstream dependencies
        run: ./install_upstream_dependencies.sh
      - name: Package up ZIP
        run: mvn --batch-mode package -DskipTests
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "kafka-connect-s3/target/components/packages/"
