name: (Maven) package and test custom Kafka Connect Connector

# For ssh debug
#  - name: Setup upterm session
#      uses: lhotari/action-upterm@v1
#      with:
#        ## limits ssh access and adds the ssh public keys of the listed GitHub users
#        limit-access-to-users: inbrewj-udc

on: [pull_request]

jobs:
  package-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"
      - name: Install upstream dependencies
        run: ./install_upstream_dependencies.sh
      - name: Package up ZIP
        run: mvn --batch-mode install -DskipTests
      - name: Run UdxStreamPartitioner unit tests
        run: mvn --batch-mode -Dtest=UdxStreamPartitionerTest -Dsurefire.failIfNoSpecifiedTests=false test
      - name: Rename and move packaged ZIP
        run: mkdir zips && cp kafka-connect-s3/target/components/packages/confluentinc-kafka-connect-s3-10.1.0-SNAPSHOT.zip zips/ && mv zips/confluentinc-kafka-connect-s3-10.1.0-SNAPSHOT.zip zips/confluentinc-kafka-connect-s3-UdxStreamPartitioner.zip
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "zips"
